### 4 NumPy数组的计算：通用函数

In [1]:
import numpy as np

# 传统输入数据方法：循环读取
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [2]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.56 s ± 26.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%timeit (1.0 / big_array)

1.01 ms ± 10.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
# 专用通用函数

from scipy import special

x = [1, 5, 10]
print(special.gamma(x), special.gammaln(x), special.beta(x, 2))

[1.0000e+00 2.4000e+01 3.6288e+05] [ 0.          3.17805383 12.80182748] [0.5        0.03333333 0.00909091]


In [6]:
x = np.array([0, 0.3, 0.7, 1.0])
print(special.erf(x), special.erfc(x), special.erfinv(x))

[0.         0.32862676 0.67780119 0.84270079] [1.         0.67137324 0.32219881 0.15729921] [0.         0.27246271 0.73286908        inf]


In [7]:
# 高级通用函数

x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]
