In [1]:
import numpy as np
print(np.__version__)

1.14.3


### 1 从Python列表创建数组

In [2]:
np.array([1, 2, 3, 4, 5], dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [3]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### 2 从头创建数组

In [4]:
np.zeros(10, dtype=np.int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3, 5), dtype=np.float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
print(np.random.random((3, 3)))
print(np.random.normal(0, 1, (3, 3)))
print(np.random.randint(0, 1000, (3, 3)))

[[0.17693811 0.60821977 0.07609218]
 [0.16593436 0.00311048 0.50331654]
 [0.97703259 0.45868609 0.51741949]]
[[ 1.5012696  -1.21774118 -1.37334245]
 [-0.44971053  0.4698882   1.41901992]
 [-0.2985299   1.11546511  0.15014418]]
[[562 575  90]
 [835 169 878]
 [298 596 647]]


In [10]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
np.empty(3)

array([0., 0., 0.])

### 3 NumPy数组操作

In [12]:
# 数组属性

np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [13]:
print(x3)
print(x3.ndim, '|', x3.shape, '|', x3.dtype, '|', x3.size, '|', x3.itemsize, '|', x3.nbytes)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
3 | (3, 4, 5) | int64 | 60 | 8 | 480


In [14]:
# 数组切片

x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
x[:5]

array([0, 1, 2, 3, 4])

In [16]:
x[5:]

array([5, 6, 7, 8, 9])

In [17]:
x[4:7]

array([4, 5, 6])

In [18]:
x[::2]

array([0, 2, 4, 6, 8])

In [19]:
x[1::2]

array([1, 3, 5, 7, 9])

In [20]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
x[5::-2]

array([5, 3, 1])

In [22]:
# 视图

x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [26]:
# 副本

x2_1 = x2[::2, ::2].copy()
print(x2)
print(x2_1)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 2]
 [1 7]]


In [28]:
# 数组变形

grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
x = np.array([1, 2, 3])
print(x)

# 通过变形获得的行向量
x.reshape((1, 3))

[1 2 3]


array([[1, 2, 3]])

In [32]:
# 通过newaxis获得的行向量
x[np.newaxis, :]

array([[1, 2, 3]])

In [33]:
# 数组拼接与分裂

x0 = np.array([1, 2, 3])
y0 = np.array([3, 2, 1])
np.concatenate([x0, y0])

array([1, 2, 3, 3, 2, 1])

In [34]:
z0 = [99, 99, 99]
print(np.concatenate([x0, y0, z0]))

[ 1  2  3  3  2  1 99 99 99]


In [36]:
# 垂直栈数组

x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [37]:
# 水平栈数组

y = np.array([[99],
[99]])
np.hstack([grid, y])

# np.dstack将沿着第三个维度拼接数组

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [43]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3, x4 = np.split(x, [3, 5, 6])
print(x1, x2, x3, x4)

[1 2 3] [99 99] [3] [2 1]


In [44]:
grid = np.arange(16).reshape((4, 4))
print(grid)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [46]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

# np.dsplit 将数组沿着第三个维度分裂。

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
