### 4 NumPy数组的计算：通用函数

In [1]:
import numpy as np

# 传统输入数据方法：循环读取
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [2]:
# big_array = np.random.randint(1, 100, size=1000000)
# %timeit compute_reciprocals(big_array)

In [3]:
# %timeit (1.0 / big_array)

In [4]:
# 专用通用函数

from scipy import special

x = [1, 5, 10]
print(special.gamma(x), special.gammaln(x), special.beta(x, 2))

[1.0000e+00 2.4000e+01 3.6288e+05] [ 0.          3.17805383 12.80182748] [0.5        0.03333333 0.00909091]


In [5]:
x = np.array([0, 0.3, 0.7, 1.0])
print(special.erf(x), special.erfc(x), special.erfinv(x))

[0.         0.32862676 0.67780119 0.84270079] [1.         0.67137324 0.32219881 0.15729921] [0.         0.27246271 0.73286908        inf]


In [6]:
# 高级通用函数

x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y) # 指定输出
print(y)

[ 0. 10. 20. 30. 40.]


In [7]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [8]:
x = np.arange(1, 6)
print(x)
np.add.reduce(x)

[1 2 3 4 5]


15

In [9]:
np.multiply.reduce(x)

120

In [10]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [11]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [12]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [13]:
# 聚合：最小值最大值与其他值

L = np.random.random(1000000)
np.sum(L)

500387.93942271615

In [14]:
print(np.max(L), np.min(L))

0.9999997207656334 7.071203171893359e-07


In [15]:
# 广播

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [16]:
M = np.ones((3, 3))
print(M)
print(M + a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [17]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)
print(a + b)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [18]:
M = np.ones((2, 3))
a = np.arange(3)
print(M, '\n', a)

[[1. 1. 1.]
 [1. 1. 1.]] 
 [0 1 2]


In [19]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [20]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a, '\n', b)

[[0]
 [1]
 [2]] 
 [0 1 2]


In [21]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [22]:
M = np.ones((3, 2))
a = np.arange(3)
print(M, '\n', a)

[[1. 1.]
 [1. 1.]
 [1. 1.]] 
 [0 1 2]


In [23]:
# M + a
# ValueError
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [24]:
# 数组归一化

X = np.random.random((10, 3))

Xmean = X.mean(0)
print(X)
print(Xmean)

[[0.85541154 0.27965023 0.95573175]
 [0.03659582 0.60934925 0.59753225]
 [0.07463842 0.43803321 0.21812627]
 [0.53159247 0.10793176 0.8448757 ]
 [0.03346237 0.32140902 0.65124221]
 [0.61473394 0.2195387  0.20020551]
 [0.71990961 0.04386778 0.24253241]
 [0.58362154 0.19365921 0.73131058]
 [0.54673692 0.34738314 0.4634587 ]
 [0.36476761 0.48515853 0.83694219]]
[0.43614702 0.30459808 0.57419576]


In [25]:
X_centered = X - Xmean
print(X_centered)
print(X_centered.mean(0))

[[ 0.41926451 -0.02494785  0.38153599]
 [-0.3995512   0.30475117  0.02333649]
 [-0.3615086   0.13343513 -0.35606949]
 [ 0.09544544 -0.19666632  0.27067994]
 [-0.40268465  0.01681094  0.07704645]
 [ 0.17858692 -0.08505938 -0.37399025]
 [ 0.28376259 -0.26073031 -0.33166335]
 [ 0.14747451 -0.11093888  0.15711482]
 [ 0.1105899   0.04278506 -0.11073705]
 [-0.07137942  0.18056044  0.26274643]]
[-4.99600361e-17  2.22044605e-17 -4.44089210e-17]


In [28]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [29]:
# 有多少值小于6？
np.count_nonzero(x < 6)

8

In [30]:
# 每行有多少值小于6？
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [31]:
# 有没有值大于8？
np.any(x > 8)

True

In [32]:
# 是否所有值都小于10？
np.all(x < 10)

True

In [34]:
# 是否每行的所有值都小于8？
np.all(x < 8, axis=0)

array([ True, False,  True,  True])